default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV["DB_USER"] %>
  password:

development:
  <<: *default
  database: cigrp_dev

test:
  <<: *default
  database: cigrp_test

production:
  url: <%= ENV["DATABASE_URL"] %>
