modules:
  - name: 'application'

wrap: true

paths:
  jquery: 'jquery'
  underscore: 'underscore/underscore'
  backbone: 'backbone/backbone'
  text: 'text/text'
  handlebars: 'handlebars/handlebars'
  moment: 'moment/moment'
  uri: 'uri.js/src'
  d3: 'd3/d3'
  foundation: 'foundation/js/foundation'
  leafletDraw: 'leaflet-draw/dist/leaflet.draw-src'

shim:
  jquery:
    exports: '$'
  underscore:
    exports: '_'
  backbone:
    deps:
      - 'jquery'
      - 'underscore'
    exports: 'Backbone'
  handlebars:
    exports: 'Handlebars'
